begin;

create table if not exists public.departments (
  id text primary key,
  name text not null unique,
  active boolean not null default true,
  display_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.employee_department_history (
  id bigint generated by default as identity primary key,
  employee_id text not null references public.employees(id),
  department_id text not null references public.departments(id),
  valid_from date not null,
  valid_to date,
  created_at timestamptz not null default now(),
  constraint employee_department_history_dates_check
    check (valid_to is null or valid_to >= valid_from),
  constraint employee_department_history_employee_start_key
    unique (employee_id, valid_from)
);

create unique index if not exists employee_department_history_current_key
  on public.employee_department_history(employee_id)
  where valid_to is null;

alter table public.employees
  add column if not exists current_department_id text references public.departments(id);

alter table public.driving_reports
  add column if not exists department_id text references public.departments(id),
  add column if not exists department_name text;

insert into public.departments (id, name, active, display_order)
values
  ('D001', '企画推進部', true, 1),
  ('D002', '安全推進部', true, 2),
  ('D003', '総務部', true, 3),
  ('D004', '第一工事部', true, 4),
  ('D005', '第二工事部', true, 5),
  ('D006', '梶が谷作業所', true, 6)
on conflict (id) do update set
  name = excluded.name,
  active = excluded.active,
  display_order = excluded.display_order,
  updated_at = now();

insert into public.employees
  (id, employee_no, name, department, current_department_id, active, display_order)
values
  ('E001', 'E001', 'テスト社員01', '企画推進部', 'D001', true, 1),
  ('E002', 'E002', 'テスト社員02', '安全推進部', 'D002', true, 2),
  ('E003', 'E003', 'テスト社員03', '総務部', 'D003', true, 3),
  ('E004', 'E004', 'テスト社員04', '第一工事部', 'D004', true, 4),
  ('E005', 'E005', 'テスト社員05', '第二工事部', 'D005', true, 5)
on conflict (id) do update set
  employee_no = excluded.employee_no,
  name = excluded.name,
  department = excluded.department,
  current_department_id = excluded.current_department_id,
  active = excluded.active,
  display_order = excluded.display_order,
  updated_at = now();

insert into public.employee_department_history
  (employee_id, department_id, valid_from, valid_to)
values
  ('E001', 'D001', date '2026-09-21', null),
  ('E002', 'D002', date '2026-09-21', null),
  ('E003', 'D003', date '2026-09-21', null),
  ('E004', 'D004', date '2026-09-21', null),
  ('E005', 'D005', date '2026-09-21', null)
on conflict (employee_id, valid_from) do update set
  department_id = excluded.department_id,
  valid_to = excluded.valid_to;

create or replace function public.apply_employee_department_change(
  p_employee_id text,
  p_department_id text,
  p_effective_date date
) returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_department_name text;
begin
  select name into v_department_name
  from public.departments
  where id = p_department_id and active = true;

  if v_department_name is null then
    raise exception 'INVALID_DEPARTMENT';
  end if;

  if not exists (select 1 from public.employees where id = p_employee_id) then
    raise exception 'INVALID_EMPLOYEE';
  end if;

  update public.employee_department_history
     set valid_to = p_effective_date - 1
   where employee_id = p_employee_id
     and valid_from < p_effective_date
     and (valid_to is null or valid_to >= p_effective_date);

  insert into public.employee_department_history
    (employee_id, department_id, valid_from, valid_to)
  values
    (p_employee_id, p_department_id, p_effective_date, null)
  on conflict (employee_id, valid_from) do update set
    department_id = excluded.department_id,
    valid_to = null;

  update public.employees
     set current_department_id = p_department_id,
         department = v_department_name,
         updated_at = now()
   where id = p_employee_id;
end;
$$;

revoke all on function public.apply_employee_department_change(text, text, date)
  from public, anon, authenticated;
grant execute on function public.apply_employee_department_change(text, text, date)
  to service_role;

create or replace function public.set_driving_report_department()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  select h.department_id, d.name
    into new.department_id, new.department_name
    from public.employee_department_history h
    join public.departments d on d.id = h.department_id
   where h.employee_id = new.employee_id
     and h.valid_from <= new.report_date
     and (h.valid_to is null or h.valid_to >= new.report_date)
   order by h.valid_from desc
   limit 1;

  if new.department_id is null then
    select e.current_department_id, e.department
      into new.department_id, new.department_name
      from public.employees e
     where e.id = new.employee_id;
  end if;

  return new;
end;
$$;

revoke all on function public.set_driving_report_department()
  from public, anon, authenticated;

drop trigger if exists driving_reports_department_snapshot
  on public.driving_reports;
create trigger driving_reports_department_snapshot
before insert or update of employee_id, report_date
on public.driving_reports
for each row execute function public.set_driving_report_department();

update public.driving_reports r
   set department_id = e.current_department_id,
       department_name = e.department
  from public.employees e
 where e.id = r.employee_id
   and r.department_id is null;

alter table public.departments enable row level security;
alter table public.employee_department_history enable row level security;

drop policy if exists departments_read_test on public.departments;
create policy departments_read_test on public.departments
for select using (true);

drop policy if exists employee_department_history_read_test
  on public.employee_department_history;
create policy employee_department_history_read_test
on public.employee_department_history
for select using (true);

grant select on public.departments to anon, authenticated;
grant select on public.employee_department_history to anon, authenticated;

commit;
